name: Python-Tests

on: [ push ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test with pytest
      run: |
        pytest

    #- name: Send Ok notification 
     # if: success() && github.ref == 'refs/heads/main'
      #uses: appleboy/telegram-action@master
      #with:
       # to: ${{ secrets.TELEGRAM_TO }}
       # token: ${{ secrets.TELEGRAM_TOKEN }}
       # args: "All tests passes"

    #- name: Send failure notification 
    #  if: failure() && github.ref == 'refs/heads/main'
    #  uses: appleboy/telegram-action@master
    #  with:
    #    to: ${{ secrets.TELEGRAM_TO }}
    #    token: ${{ secrets.TELEGRAM_TOKEN }}
    #    args: "Tests failed"
